title: Your awesome title
lang: en
description: Write an awesome description for your new site here

remote_theme: rundocs/jekyll-rtd-theme


readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jemoji
  - jekyll-avatar
  - jekyll-mentions


